### ISSUE TITLE
Implement transparency to reveal culled vertices

### ISSUE THREAD

**Issue by ccp-codex** [Jim-Eckerlein/pentachoron#20]
Hi Jim. Great work! Not really an issue but a feature request or guidance how to implement such a feature... I'd love to be able to see the culled vertices per this example from Wikipedia : [A 3D projection of a 5-cell performing a simple rotation](https://en.wikipedia.org/wiki/5-cell#/media/File:5-cell.gif) via either a transparency effect or some other method. Any guidance much appreciated.

**Comment by Jim-Eckerlein** [comment]
Thank you, I always appreciate feedback.

To make things clear, the animation from Wikipedia displays a projection of a pentachoron in the 3d space, while my app computes an intersection of an hyperspace geometry with the 3d space where the fourth component is zero. I wrote more about the concept [here](https://jim-eckerlein.io/#pentachoron), I won't paste it here because it contains some Latex markup.

The idea of drawing the geometry transparent is actually pretty good and it should be possible to implement such a feature. The only thing to keep in mind is that this app is based on Flutter, which itself uses Skia to render 2d graphics. Flutter was at the time of writing the app not able to expose the underlying OpenGL context, so I was forced to implement a 3d renderer by hand, using Flutters 2d canvas widget. This really limits the vertex throughput, and completely rules out any per-pixel shaders. Transparency by itself should work, but refraction and reflection like in the animation on Wikipedia won't be possible.

The 3d renderer is implemented [here](https://github.com/Jim-Eckerlein/pentachoron/blob/develop/lib/canvas3d/painter.dart). This is the first place to go when changing the draw routine. The line 95 actually draws the triangles. Because there is no z-buffer, the triangles are depth-sorted first, which is necessary for transparency as well.

I currently don't have time to add it myself, but feel free to implement such a feature.

**Comment by ccp-codex** [comment]
Thanks so much for the guidance Jim. I'm in no way a 3D programmer so it'll probably take some time spelunking to come up with anything interesting I can commit back but I will once I'm there.

**Comment by Jim-Eckerlein** [comment]
If you're generally interested in 3D graphics, check out this [website](https://www.scratchapixel.com/index.php?#_=_).
Especially it's [chapter about matrices](https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/geometry/matrices) is important to understand, because the renderer extrudes the concept of matrices into the 5th dimension. (4 dimensions to build the base and one to represent translation).

**Comment by ccp-codex** [comment]
I created a BountySource funding thing for this. Not sure the best way to display it here but hope someone comes along with the time to do the work and claim the bounty. :)

https://www.bountysource.com/issues/74079443-transparency-or-other-technique-to-reveal-culled-vertices

**Comment by Jim-Eckerlein** [comment]
I'm okay with that.

**Comment by Azorlogh** [comment]
I have added transparency as a slider setting.

The transparency itself wasn't hard to implement.

The only problem was that the hull generation algorithm was generating duplicate faces on quads, which made the transparency look wrong in some places.
Therefore I added some code to detect and remove the duplicate faces.

I have also made it so that the backward-facing triangles show when there is transparency.

I made the pull request for the changes, Let me know what you think !

**Comment by Jim-Eckerlein** [comment]
The result looks good, transparency works quite well.
Only problem is that the "Transparency" label next to slider is wrapped in the middle of the word, but I'll fix that myself, as that is more related to the UI.

**Comment by Jim-Eckerlein** [comment]
@Azorlogh  I think the bounty is yours. 👍

**Comment by Azorlogh** [comment]
Glad to see you're happy with the result!

**Comment by ccp-codex** [comment]
I don't know if there's anything I need to do on my end as far as the bounty is concerned but will check tonight and press the buttons to make the award happen. I kind of dig this bounty source business. If I had more money I'd like it a lot more. :P

**Comment by Azorlogh** [comment]
Once the GitHub issue is closed I should be able to claim it.
Yeah, I'm happy this exists! As a student, working on these problems and getting paid in the end is very rewarding and I learn a lot along the way, so thanks for contributing.
Also thanks Jim for raising the bounty after the delivery. : )

**Comment by Jim-Eckerlein** [comment]
I'm closing the issue now, thanks for implementing the feature. Works like a charm.
