### ISSUE TITLE
Add option to display a projection of a pentachoron in 3d space and perform a simple rotation

### ISSUE THREAD

**Issue by ccp-codex** [Jim-Eckerlein/pentachoron#22]
Hi Jim, 

I'm considering another bounty to add an option to display a projection of the pentachoron in 3d space and perform a simple rotation per the example on wikipedia minus the translucency effect in the gif:

https://en.wikipedia.org/wiki/5-cell#Projections

https://upload.wikimedia.org/wikipedia/commons/d/d8/5-cell.gif

If you think this is an appropriate issue for this project and don't mind me providing a bounty let me know and feel free to enrich the statement of work as you see fit.

**Comment by Jim-Eckerlein** [comment]
Sounds great, but involves more work than the transparency effect.
The app would need to have two modes of 4d rendering:

- Intersection with the 3d space
- Projection into the 3d space

I've made a sketch (translating the problem to a ℝ ³⟶ ℝ ² mapping) to better visualize the difference between the modes.

![001](https://user-images.githubusercontent.com/13494482/59852632-7e3b9e00-936f-11e9-91f9-8c9d081887ab.jpg)

So I think this is absolutely an appropriate issue, and it'd be amazing if it worked out.

**Comment by Azorlogh** [comment]
Do you want to tackle this issue yourself ? Otherwise, I'd be interested in trying to implement it.

**Comment by Jim-Eckerlein** [comment]
I'm studying and am working on another hobby project, so I haven't the time to implement it. I would be glad if you try it, though. :+1:

**Comment by ccp-codex** [comment]
There's some very interesting sample code by Meiko Rachmiow written in Java using Java3D here:

https://web.archive.org/web/20110718202453/http://public.beuth-hochschule.de/~meiko/pentatope.html

It assumes access to a scene graph but doesn't rely heavily on esoteric capabilities so might be helpful in porting.

https://web.archive.org/web/20110718202453/http://public.beuth-hochschule.de/~meiko/pentatope.html

Of particular interest is the source available here :

**Comment by ccp-codex** [comment]
@Azorlogh @Jim-Eckerlein 

Added a bounty for $240 USD here : https://www.bountysource.com/issues/75707702-add-option-to-display-a-projection-of-a-pentachoron-in-3d-space-and-perform-a-simple-rotation

**Comment by Jim-Eckerlein** [comment]
Great. I just raised the bounty a bit.

**Comment by ccp-codex** [comment]
@Jim-Eckerlein @Azorlogh

I just raised the bounty so it's now at $360USD and did another promotional tweet. Crossing my fingers! :) 

https://www.bountysource.com/issues/75707702-add-option-to-display-a-projection-of-a-pentachoron-in-3d-space-and-perform-a-simple-rotation

**Comment by Jim-Eckerlein** [comment]
Great

**Comment by Azorlogh** [comment]
Thanks, I should send more updates on the progress. I've had some other stuff going on in my life but I'm still working on this.

Here's the progress :

- I have changed the rendering to use tetrahedrons (that I just slice at render time to get polygons) instead of a set of lines, for two reasons:

1) In slicing mode, there's no need to construct the convex hull of the set of intersection points anymore, so it should be faster and more general

2) In projection mode, it allows me to easily extract all the polygons, some of which now lie inside the shape instead of only the surface

What I'm still working out :

Since the shape in projection mode isn't a simple convex volume, I have to modify the sorting algorithm of the polygons, because otherwise, simply looking at the depth of the barycenter of the polygons to determine their drawing order doesn't produce the right order in some rotations.

Right now, to sort A and B, I'm trying to look if A and B will overlap in the render, and if they will, slice only the part of A and B where they overlap, and use barycenter depth on the pieces to know if A is over B or the opposite.
This is almost working but I need to fix something with the slicing.

After that, if all goes well, I'll just have to clean up some stuff and add buttons to switch render modes :)

**Comment by Jim-Eckerlein** [comment]
Sounds great!

**Comment by ccp-codex** [comment]
Looking forward to seeing the results!

**Comment by Jim-Eckerlein** [comment]
@Azorlogh How is it going? Would be great to hear from you if you are still working on it.

**Comment by Azorlogh** [comment]
Hi, I'm not going to finish this unfortunately. I'm sorry.
Things were tougher than I expected and I couldn't manage to properly order the faces in all orientations.
I'm leaving this issue to anyone who may be interested in taking this on, or for cpp-codex to be refunded.

**Comment by Jim-Eckerlein** [comment]
Ok, I think I'll close the issue. @ccp-codex could you issue a refund on Bounty Source? Seems that I cannot do that because I have not created the bounty.

**Comment by Jim-Eckerlein** [comment]
I'm closing the issue now with status "won't solve".
